import Head from "next/head";
import Sidebar from "../sidebar/sidebar";
import { useRouter } from "next/router";
export default function MainLayout({ children, keywords = " " }) {
  function capitalize(string) {
    return string[0].toUpperCase() + string.slice(1);
  }
  const query = useRouter();

  return (
    <>
      <Head>
        <title>
          Portfolio RC |{" "}
          {query.pathname.slice(1)
            ? capitalize(query.pathname.slice(1))
            : "Home"}
        </title>
        <meta keywords={"Portfolio RC, " + keywords}></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Clicker+Script&display=swap"
          rel="stylesheet"></link>
      </Head>
      <main>
        <div className="flex">
          <Sidebar />

          <div className="flex-1">{children}</div>
        </div>
      </main>
    </>
  );
}
